---
name: Build RPM
on: 
  workflow_dispatch:
    inputs:
      distribuition:
        description: 'Define distro version'     
        required: false
        default: 'centos-7'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rpmbuild        
        uses: robertdebock/rpmbuild-action@1.0.0
