name: Build RPM
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rpmbuild
        with:
          distribution: centos-7
        uses: robertdebock/rpmbuild-action@1.0.0
